// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: bcbpb/bcbpb.proto

package bcbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BCBMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*BCBMessage_StartMessage
	//	*BCBMessage_EchoMessage
	//	*BCBMessage_FinalMessage
	Type isBCBMessage_Type `protobuf_oneof:"type"`
}

func (x *BCBMessage) Reset() {
	*x = BCBMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcbpb_bcbpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BCBMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BCBMessage) ProtoMessage() {}

func (x *BCBMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bcbpb_bcbpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BCBMessage.ProtoReflect.Descriptor instead.
func (*BCBMessage) Descriptor() ([]byte, []int) {
	return file_bcbpb_bcbpb_proto_rawDescGZIP(), []int{0}
}

func (m *BCBMessage) GetType() isBCBMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *BCBMessage) GetStartMessage() *StartMessage {
	if x, ok := x.GetType().(*BCBMessage_StartMessage); ok {
		return x.StartMessage
	}
	return nil
}

func (x *BCBMessage) GetEchoMessage() *EchoMessage {
	if x, ok := x.GetType().(*BCBMessage_EchoMessage); ok {
		return x.EchoMessage
	}
	return nil
}

func (x *BCBMessage) GetFinalMessage() *FinalMessage {
	if x, ok := x.GetType().(*BCBMessage_FinalMessage); ok {
		return x.FinalMessage
	}
	return nil
}

type isBCBMessage_Type interface {
	isBCBMessage_Type()
}

type BCBMessage_StartMessage struct {
	StartMessage *StartMessage `protobuf:"bytes,1,opt,name=start_message,json=startMessage,proto3,oneof"`
}

type BCBMessage_EchoMessage struct {
	EchoMessage *EchoMessage `protobuf:"bytes,2,opt,name=echo_message,json=echoMessage,proto3,oneof"`
}

type BCBMessage_FinalMessage struct {
	FinalMessage *FinalMessage `protobuf:"bytes,3,opt,name=final_message,json=finalMessage,proto3,oneof"`
}

func (*BCBMessage_StartMessage) isBCBMessage_Type() {}

func (*BCBMessage_EchoMessage) isBCBMessage_Type() {}

func (*BCBMessage_FinalMessage) isBCBMessage_Type() {}

type StartMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StartMessage) Reset() {
	*x = StartMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcbpb_bcbpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMessage) ProtoMessage() {}

func (x *StartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bcbpb_bcbpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMessage.ProtoReflect.Descriptor instead.
func (*StartMessage) Descriptor() ([]byte, []int) {
	return file_bcbpb_bcbpb_proto_rawDescGZIP(), []int{1}
}

func (x *StartMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcbpb_bcbpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bcbpb_bcbpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file_bcbpb_bcbpb_proto_rawDescGZIP(), []int{2}
}

func (x *EchoMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type FinalMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signers    []string `protobuf:"bytes,2,rep,name=signers,proto3" json:"signers,omitempty"`
	Signatures [][]byte `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *FinalMessage) Reset() {
	*x = FinalMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcbpb_bcbpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalMessage) ProtoMessage() {}

func (x *FinalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bcbpb_bcbpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalMessage.ProtoReflect.Descriptor instead.
func (*FinalMessage) Descriptor() ([]byte, []int) {
	return file_bcbpb_bcbpb_proto_rawDescGZIP(), []int{3}
}

func (x *FinalMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FinalMessage) GetSigners() []string {
	if x != nil {
		return x.Signers
	}
	return nil
}

func (x *FinalMessage) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_bcbpb_bcbpb_proto protoreflect.FileDescriptor

var file_bcbpb_bcbpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x63, 0x62, 0x70, 0x62, 0x2f, 0x62, 0x63, 0x62, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62, 0x63, 0x62, 0x70, 0x62, 0x22, 0xc5, 0x01, 0x0a, 0x0a, 0x42,
	0x43, 0x42, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x63, 0x62, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x63,
	0x62, 0x70, 0x62, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x0b, 0x65, 0x63, 0x68, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a,
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x63, 0x62, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0x5c, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x63, 0x6f, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2f, 0x6d, 0x69, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x63, 0x62, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bcbpb_bcbpb_proto_rawDescOnce sync.Once
	file_bcbpb_bcbpb_proto_rawDescData = file_bcbpb_bcbpb_proto_rawDesc
)

func file_bcbpb_bcbpb_proto_rawDescGZIP() []byte {
	file_bcbpb_bcbpb_proto_rawDescOnce.Do(func() {
		file_bcbpb_bcbpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_bcbpb_bcbpb_proto_rawDescData)
	})
	return file_bcbpb_bcbpb_proto_rawDescData
}

var file_bcbpb_bcbpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bcbpb_bcbpb_proto_goTypes = []interface{}{
	(*BCBMessage)(nil),   // 0: bcbpb.BCBMessage
	(*StartMessage)(nil), // 1: bcbpb.StartMessage
	(*EchoMessage)(nil),  // 2: bcbpb.EchoMessage
	(*FinalMessage)(nil), // 3: bcbpb.FinalMessage
}
var file_bcbpb_bcbpb_proto_depIdxs = []int32{
	1, // 0: bcbpb.BCBMessage.start_message:type_name -> bcbpb.StartMessage
	2, // 1: bcbpb.BCBMessage.echo_message:type_name -> bcbpb.EchoMessage
	3, // 2: bcbpb.BCBMessage.final_message:type_name -> bcbpb.FinalMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bcbpb_bcbpb_proto_init() }
func file_bcbpb_bcbpb_proto_init() {
	if File_bcbpb_bcbpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bcbpb_bcbpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BCBMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcbpb_bcbpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcbpb_bcbpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcbpb_bcbpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bcbpb_bcbpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BCBMessage_StartMessage)(nil),
		(*BCBMessage_EchoMessage)(nil),
		(*BCBMessage_FinalMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bcbpb_bcbpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcbpb_bcbpb_proto_goTypes,
		DependencyIndexes: file_bcbpb_bcbpb_proto_depIdxs,
		MessageInfos:      file_bcbpb_bcbpb_proto_msgTypes,
	}.Build()
	File_bcbpb_bcbpb_proto = out.File
	file_bcbpb_bcbpb_proto_rawDesc = nil
	file_bcbpb_bcbpb_proto_goTypes = nil
	file_bcbpb_bcbpb_proto_depIdxs = nil
}
