package codegen

import (
	"fmt"
	"go/ast"
	"reflect"

	"github.com/dave/jennifer/jen"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/filecoin-project/mir/codegen/proto-converter/util/astutil"
	"github.com/filecoin-project/mir/codegen/proto-converter/util/jenutil"
	"github.com/filecoin-project/mir/codegen/proto-converter/util/protoreflectutil"
)

// Message contains the information needed to generate code for a protobuf message.
type Message struct {
	fields               Fields
	pbStructType         jen.Code
	mirStructType        jen.Code
	protoDesc            protoreflect.MessageDescriptor
	pbGoStructPtrReflect reflect.Type
}

func (m *Message) Name() string {
	return m.pbGoStructPtrReflect.Elem().Name()
}

func (m *Message) MirPkgPath() string {
	return StructsPackagePath(m.pbGoStructPtrReflect.Elem().PkgPath())
}

func (m *Message) PbType() jen.Code {
	return jen.Op("*").Add(m.pbStructType)
}

func (m *Message) NewPbType() jen.Code {
	return jen.Op("&").Add(m.pbStructType)
}

func (m *Message) NewMirType() jen.Code {
	return jen.Op("&").Add(m.mirStructType)
}

func (m *Message) MirType() jen.Code {
	return jen.Op("*").Add(m.mirStructType)
}

func (m *Message) ToMir(code jen.Code) jen.Code {
	return jen.Qual(m.MirPkgPath(), m.Name()+"FromPb").Call(code)
}

func (m *Message) ToPb(code jen.Code) jen.Code {
	return jen.Add(code).Dot("Pb").Call()
}

// LowercaseName returns the name of the message in lowercase.
func (m *Message) LowercaseName() string {
	return astutil.ToUnexported(m.Name())
}

func (m *Message) FuncParamPbType() jen.Code {
	return jen.Id(m.LowercaseName()).Add(m.PbType())
}

func (m *Message) FuncParamMirType() jen.Code {
	return jen.Id(m.LowercaseName()).Add(m.MirType())
}

func (m *Message) StructParamPbType() jen.Code {
	return jen.Id(m.Name()).Add(m.PbType())
}

func (m *Message) StructParamMirType() jen.Code {
	return jen.Id(m.Name()).Add(m.MirType())
}

// MessageFromPbGoType returns the message corresponding to the given protobuf-generated struct type.
func MessageFromPbGoType(pbGoStructPtr reflect.Type) (*Message, error) {
	protoDesc, ok := protoreflectutil.DescriptorForType(pbGoStructPtr)
	if !ok {
		return nil, fmt.Errorf("%T is not a protobuf message", pbGoStructPtr)
	}

	pbStructType := jenutil.QualFromType(pbGoStructPtr.Elem())

	shouldGenerateMirStruct := IsMirEvent(protoDesc) || IsMirMessage(protoDesc) || IsMirStruct(protoDesc)

	var pkgPath string
	var mirStructType jen.Code
	if shouldGenerateMirStruct {
		// The type of the struct that will be generated.
		pkgPath = StructsPackagePath(pbGoStructPtr.Elem().PkgPath())
		mirStructType = jen.Qual(pkgPath, pbGoStructPtr.Elem().Name())
	} else {
		// The original type generated by protoc.
		pkgPath = pbGoStructPtr.Elem().PkgPath()
		mirStructType = pbStructType
	}

	return &Message{
		pbStructType:         pbStructType,
		mirStructType:        mirStructType,
		protoDesc:            protoDesc,
		pbGoStructPtrReflect: pbGoStructPtr,
	}, nil
}

func (m *Message) Fields() (Fields, error) {
	// Return the cached value if present.
	if m.fields != nil {
		return m.fields, nil
	}

	for i := 0; i < m.pbGoStructPtrReflect.Elem().NumField(); i++ {
		// Get go representation of the field.
		goField := m.pbGoStructPtrReflect.Elem().Field(i)
		if !ast.IsExported(goField.Name) {
			// Skip unexported fields.
			continue
		}

		if oneofTag, ok := goField.Tag.Lookup("protobuf_oneof"); ok {
			_ = oneofTag
			// TODO: oneofs are skipped for now.
			continue
		}

		// Get protobuf representation of the field.
		protoName, err := getProtoNameOfField(goField)
		if err != nil {
			return nil, err
		}
		protoField := m.protoDesc.Fields().ByName(protoreflect.Name(protoName))

		// Create the Field struct.
		field, err := GetField(goField, protoField)
		if err != nil {
			return nil, err
		}

		m.fields = append(m.fields, field)
	}

	return m.fields, nil
}

func (m *Message) IsMirEvent() bool {
	return IsMirEvent(m.protoDesc)
}

func (m *Message) IsMirMessage() bool {
	return IsMirMessage(m.protoDesc)
}

func (m *Message) IsMirStruct() bool {
	return IsMirStruct(m.protoDesc)
}

// ShouldGenerateMirType returns true if Mir should generate a struct for the message type.
func (m *Message) ShouldGenerateMirType() bool {
	return ShouldGenerateMirType(m.protoDesc)
}
