package codegen

import (
	"fmt"
	"go/ast"
	"reflect"

	"github.com/dave/jennifer/jen"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/filecoin-project/mir/codegen/proto-converter/util/astutil"
	"github.com/filecoin-project/mir/codegen/proto-converter/util/jenutil"
	"github.com/filecoin-project/mir/codegen/proto-converter/util/protoreflectutil"
)

// Message contains the information needed to generate code for a protobuf message.
type Message struct {
	fields Fields

	PkgPath              string
	Name                 string
	PbType               jen.Code
	MirType              jen.Code
	ProtoDesc            protoreflect.MessageDescriptor
	ReflectPbGoStructPtr reflect.Type
}

// PbTypePtr returns the code corresponding to the type of the pointer to the protoc-generated struct.
func (m *Message) PbTypePtr() jen.Code {
	return jen.Op("*").Add(m.PbType)
}

// MirTypePtr returns the code corresponding to the type of the pointer to the Mir-generated struct.
func (m *Message) MirTypePtr() jen.Code {
	return jen.Op("*").Add(m.MirType)
}

// FromPbFunc returns the name of the function that converts a protobuf-generated struct to a Mir-generated struct.
func (m *Message) FromPbFunc() jen.Code {
	return jen.Qual(m.PkgPath, m.Name+"FromPb")
}

// ToPbFunc returns the name of the function that converts a Mir-generated struct to a protobuf-generated struct.
func (m *Message) ToPbFunc() jen.Code {
	return jen.Qual(m.PkgPath, m.Name+"ToPb")
}

// LowercaseName returns the name of the message in lowercase.
func (m *Message) LowercaseName() string {
	return astutil.ToUnexported(m.Name)
}

func (m *Message) FuncParamPbType() jen.Code {
	return jen.Id(m.LowercaseName()).Add(m.PbTypePtr())
}

func (m *Message) FuncParamMirType() jen.Code {
	return jen.Id(m.LowercaseName()).Add(m.MirType)
}

func (m *Message) StructParamPbType() jen.Code {
	return jen.Id(m.Name).Add(m.PbType)
}

func (m *Message) StructParamMirType() jen.Code {
	return jen.Id(m.Name).Add(m.MirType)
}

// MessageFromPbGoType returns the message corresponding to the given protobuf-generated struct type.
func MessageFromPbGoType(pbGoStructPtr reflect.Type) (*Message, error) {
	protoDesc, ok := protoreflectutil.DescriptorForType(pbGoStructPtr)
	if !ok {
		return nil, fmt.Errorf("%T is not a protobuf message", pbGoStructPtr)
	}

	pbType := jenutil.QualFromType(pbGoStructPtr.Elem())

	shouldGenerateMirStruct := IsMirEvent(protoDesc) || IsMirMessage(protoDesc) || IsMirStruct(protoDesc)

	var pkgPath string
	var mirType jen.Code
	if shouldGenerateMirStruct {
		// The type of the struct that will be generated.
		pkgPath = StructsPackagePath(pbGoStructPtr.Elem().PkgPath())
		mirType = jen.Qual(pkgPath, pbGoStructPtr.Elem().Name())
	} else {
		// The original type generated by protoc.
		pkgPath = pbGoStructPtr.Elem().PkgPath()
		mirType = pbType
	}

	return &Message{
		PkgPath:              pkgPath,
		Name:                 pbGoStructPtr.Elem().Name(),
		PbType:               pbType,
		MirType:              mirType,
		ProtoDesc:            protoDesc,
		ReflectPbGoStructPtr: pbGoStructPtr,
	}, nil
}

func (m *Message) Fields() (Fields, error) {
	// Return the cached value if present.
	if m.fields != nil {
		return m.fields, nil
	}

	for i := 0; i < m.ReflectPbGoStructPtr.Elem().NumField(); i++ {
		// Get go representation of the field.
		goField := m.ReflectPbGoStructPtr.Elem().Field(i)
		if !ast.IsExported(goField.Name) {
			// Skip unexported fields.
			continue
		}

		if oneofTag, ok := goField.Tag.Lookup("protobuf_oneof"); ok {
			_ = oneofTag
			// TODO: oneofs are skipped for now.
			continue
		}

		// Get protobuf representation of the field.
		protoName, err := getProtoNameOfField(goField)
		if err != nil {
			return nil, err
		}
		protoField := m.ProtoDesc.Fields().ByName(protoreflect.Name(protoName))

		// Create the Field struct.
		field, err := GetField(goField, protoField)
		if err != nil {
			return nil, err
		}

		m.fields = append(m.fields, field)
	}

	return m.fields, nil
}

func (m *Message) IsMirEvent() bool {
	return IsMirEvent(m.ProtoDesc)
}

func (m *Message) IsMirMessage() bool {
	return IsMirMessage(m.ProtoDesc)
}

func (m *Message) IsMirStruct() bool {
	return IsMirStruct(m.ProtoDesc)
}

// ShouldGenerateMirType returns true if Mir should generate a struct for the message type.
func (m *Message) ShouldGenerateMirType() bool {
	return ShouldGenerateMirType(m.ProtoDesc)
}
