// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: mempoolpb/mempoolpb.proto

package mempoolpb

import (
	contextstorepb "github.com/filecoin-project/mir/pkg/pb/contextstorepb"
	dslpb "github.com/filecoin-project/mir/pkg/pb/dslpb"
	_ "github.com/filecoin-project/mir/pkg/pb/mir"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Event_NewTransactions
	//	*Event_RequestTransactions
	//	*Event_TransactionsResponse
	Type isEvent_Type `protobuf_oneof:"Type"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolpb_mempoolpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolpb_mempoolpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mempoolpb_mempoolpb_proto_rawDescGZIP(), []int{0}
}

func (m *Event) GetType() isEvent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Event) GetNewTransactions() *NewTransactions {
	if x, ok := x.GetType().(*Event_NewTransactions); ok {
		return x.NewTransactions
	}
	return nil
}

func (x *Event) GetRequestTransactions() *RequestTransactions {
	if x, ok := x.GetType().(*Event_RequestTransactions); ok {
		return x.RequestTransactions
	}
	return nil
}

func (x *Event) GetTransactionsResponse() *TransactionsResponse {
	if x, ok := x.GetType().(*Event_TransactionsResponse); ok {
		return x.TransactionsResponse
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_NewTransactions struct {
	NewTransactions *NewTransactions `protobuf:"bytes,1,opt,name=new_transactions,json=newTransactions,proto3,oneof"`
}

type Event_RequestTransactions struct {
	RequestTransactions *RequestTransactions `protobuf:"bytes,2,opt,name=request_transactions,json=requestTransactions,proto3,oneof"`
}

type Event_TransactionsResponse struct {
	TransactionsResponse *TransactionsResponse `protobuf:"bytes,3,opt,name=transactions_response,json=transactionsResponse,proto3,oneof"`
}

func (*Event_NewTransactions) isEvent_Type() {}

func (*Event_RequestTransactions) isEvent_Type() {}

func (*Event_TransactionsResponse) isEvent_Type() {}

type NewTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxIds [][]byte `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"`
}

func (x *NewTransactions) Reset() {
	*x = NewTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolpb_mempoolpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTransactions) ProtoMessage() {}

func (x *NewTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolpb_mempoolpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTransactions.ProtoReflect.Descriptor instead.
func (*NewTransactions) Descriptor() ([]byte, []int) {
	return file_mempoolpb_mempoolpb_proto_rawDescGZIP(), []int{1}
}

func (x *NewTransactions) GetTxIds() [][]byte {
	if x != nil {
		return x.TxIds
	}
	return nil
}

type RequestTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxIds  [][]byte                   `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"`
	Origin *RequestTransactionsOrigin `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *RequestTransactions) Reset() {
	*x = RequestTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolpb_mempoolpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTransactions) ProtoMessage() {}

func (x *RequestTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolpb_mempoolpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTransactions.ProtoReflect.Descriptor instead.
func (*RequestTransactions) Descriptor() ([]byte, []int) {
	return file_mempoolpb_mempoolpb_proto_rawDescGZIP(), []int{2}
}

func (x *RequestTransactions) GetTxIds() [][]byte {
	if x != nil {
		return x.TxIds
	}
	return nil
}

func (x *RequestTransactions) GetOrigin() *RequestTransactionsOrigin {
	if x != nil {
		return x.Origin
	}
	return nil
}

type TransactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs    [][]byte                   `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	Origin *RequestTransactionsOrigin `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *TransactionsResponse) Reset() {
	*x = TransactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolpb_mempoolpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsResponse) ProtoMessage() {}

func (x *TransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolpb_mempoolpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsResponse.ProtoReflect.Descriptor instead.
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return file_mempoolpb_mempoolpb_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionsResponse) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *TransactionsResponse) GetOrigin() *RequestTransactionsOrigin {
	if x != nil {
		return x.Origin
	}
	return nil
}

type RequestTransactionsOrigin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Types that are assignable to Type:
	//	*RequestTransactionsOrigin_ContextStore
	//	*RequestTransactionsOrigin_Dsl
	Type isRequestTransactionsOrigin_Type `protobuf_oneof:"Type"`
}

func (x *RequestTransactionsOrigin) Reset() {
	*x = RequestTransactionsOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolpb_mempoolpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTransactionsOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTransactionsOrigin) ProtoMessage() {}

func (x *RequestTransactionsOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolpb_mempoolpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTransactionsOrigin.ProtoReflect.Descriptor instead.
func (*RequestTransactionsOrigin) Descriptor() ([]byte, []int) {
	return file_mempoolpb_mempoolpb_proto_rawDescGZIP(), []int{4}
}

func (x *RequestTransactionsOrigin) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (m *RequestTransactionsOrigin) GetType() isRequestTransactionsOrigin_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *RequestTransactionsOrigin) GetContextStore() *contextstorepb.Origin {
	if x, ok := x.GetType().(*RequestTransactionsOrigin_ContextStore); ok {
		return x.ContextStore
	}
	return nil
}

func (x *RequestTransactionsOrigin) GetDsl() *dslpb.Origin {
	if x, ok := x.GetType().(*RequestTransactionsOrigin_Dsl); ok {
		return x.Dsl
	}
	return nil
}

type isRequestTransactionsOrigin_Type interface {
	isRequestTransactionsOrigin_Type()
}

type RequestTransactionsOrigin_ContextStore struct {
	ContextStore *contextstorepb.Origin `protobuf:"bytes,2,opt,name=context_store,json=contextStore,proto3,oneof"`
}

type RequestTransactionsOrigin_Dsl struct {
	Dsl *dslpb.Origin `protobuf:"bytes,3,opt,name=dsl,proto3,oneof"`
}

func (*RequestTransactionsOrigin_ContextStore) isRequestTransactionsOrigin_Type() {}

func (*RequestTransactionsOrigin_Dsl) isRequestTransactionsOrigin_Type() {}

var File_mempoolpb_mempoolpb_proto protoreflect.FileDescriptor

var file_mempoolpb_mempoolpb_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x6d, 0x70,
	0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65, 0x6d,
	0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x1a, 0x23, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x64, 0x73, 0x6c,
	0x70, 0x62, 0x2f, 0x64, 0x73, 0x6c, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x6d, 0x69, 0x72, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x10, 0x6e, 0x65,
	0x77, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62,
	0x2e, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x48, 0x00, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x53, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x48, 0x00, 0x52, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x56, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f,
	0x6c, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x14, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x22, 0x28,
	0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x05, 0x74, 0x78, 0x49, 0x64, 0x73, 0x22, 0x6a, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x78, 0x49, 0x64, 0x73, 0x12, 0x3c, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x22, 0x66, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x3c,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x9d, 0x01, 0x0a,
	0x19, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x48, 0x00, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x73, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x64, 0x73, 0x6c, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52,
	0x03, 0x64, 0x73, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x63,
	0x6f, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x69, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mempoolpb_mempoolpb_proto_rawDescOnce sync.Once
	file_mempoolpb_mempoolpb_proto_rawDescData = file_mempoolpb_mempoolpb_proto_rawDesc
)

func file_mempoolpb_mempoolpb_proto_rawDescGZIP() []byte {
	file_mempoolpb_mempoolpb_proto_rawDescOnce.Do(func() {
		file_mempoolpb_mempoolpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_mempoolpb_mempoolpb_proto_rawDescData)
	})
	return file_mempoolpb_mempoolpb_proto_rawDescData
}

var file_mempoolpb_mempoolpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mempoolpb_mempoolpb_proto_goTypes = []interface{}{
	(*Event)(nil),                     // 0: mempoolpb.Event
	(*NewTransactions)(nil),           // 1: mempoolpb.NewTransactions
	(*RequestTransactions)(nil),       // 2: mempoolpb.RequestTransactions
	(*TransactionsResponse)(nil),      // 3: mempoolpb.TransactionsResponse
	(*RequestTransactionsOrigin)(nil), // 4: mempoolpb.RequestTransactionsOrigin
	(*contextstorepb.Origin)(nil),     // 5: contextstorepb.Origin
	(*dslpb.Origin)(nil),              // 6: dslpb.Origin
}
var file_mempoolpb_mempoolpb_proto_depIdxs = []int32{
	1, // 0: mempoolpb.Event.new_transactions:type_name -> mempoolpb.NewTransactions
	2, // 1: mempoolpb.Event.request_transactions:type_name -> mempoolpb.RequestTransactions
	3, // 2: mempoolpb.Event.transactions_response:type_name -> mempoolpb.TransactionsResponse
	4, // 3: mempoolpb.RequestTransactions.origin:type_name -> mempoolpb.RequestTransactionsOrigin
	4, // 4: mempoolpb.TransactionsResponse.origin:type_name -> mempoolpb.RequestTransactionsOrigin
	5, // 5: mempoolpb.RequestTransactionsOrigin.context_store:type_name -> contextstorepb.Origin
	6, // 6: mempoolpb.RequestTransactionsOrigin.dsl:type_name -> dslpb.Origin
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mempoolpb_mempoolpb_proto_init() }
func file_mempoolpb_mempoolpb_proto_init() {
	if File_mempoolpb_mempoolpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mempoolpb_mempoolpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolpb_mempoolpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolpb_mempoolpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolpb_mempoolpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolpb_mempoolpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTransactionsOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mempoolpb_mempoolpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_NewTransactions)(nil),
		(*Event_RequestTransactions)(nil),
		(*Event_TransactionsResponse)(nil),
	}
	file_mempoolpb_mempoolpb_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RequestTransactionsOrigin_ContextStore)(nil),
		(*RequestTransactionsOrigin_Dsl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mempoolpb_mempoolpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mempoolpb_mempoolpb_proto_goTypes,
		DependencyIndexes: file_mempoolpb_mempoolpb_proto_depIdxs,
		MessageInfos:      file_mempoolpb_mempoolpb_proto_msgTypes,
	}.Build()
	File_mempoolpb_mempoolpb_proto = out.File
	file_mempoolpb_mempoolpb_proto_rawDesc = nil
	file_mempoolpb_mempoolpb_proto_goTypes = nil
	file_mempoolpb_mempoolpb_proto_depIdxs = nil
}
