// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: protoutil_testpb.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoutil_testpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_protoutil_testpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_protoutil_testpb_proto_rawDescGZIP(), []int{0}
}

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to BarOrBaz:
	//	*Foo_BarOption
	//	*Foo_BazOption
	BarOrBaz isFoo_BarOrBaz `protobuf_oneof:"bar_or_baz"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoutil_testpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_protoutil_testpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_protoutil_testpb_proto_rawDescGZIP(), []int{1}
}

func (m *Foo) GetBarOrBaz() isFoo_BarOrBaz {
	if m != nil {
		return m.BarOrBaz
	}
	return nil
}

func (x *Foo) GetBarOption() *Bar {
	if x, ok := x.GetBarOrBaz().(*Foo_BarOption); ok {
		return x.BarOption
	}
	return nil
}

func (x *Foo) GetBazOption() uint64 {
	if x, ok := x.GetBarOrBaz().(*Foo_BazOption); ok {
		return x.BazOption
	}
	return 0
}

type isFoo_BarOrBaz interface {
	isFoo_BarOrBaz()
}

type Foo_BarOption struct {
	BarOption *Bar `protobuf:"bytes,1,opt,name=bar_option,json=barOption,proto3,oneof"`
}

type Foo_BazOption struct {
	BazOption uint64 `protobuf:"varint,2,opt,name=baz_option,json=bazOption,proto3,oneof"`
}

func (*Foo_BarOption) isFoo_BarOrBaz() {}

func (*Foo_BazOption) isFoo_BarOrBaz() {}

var File_protoutil_testpb_proto protoreflect.FileDescriptor

var file_protoutil_testpb_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x75, 0x74, 0x69, 0x6c, 0x5f, 0x74, 0x65, 0x73, 0x74,
	0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62,
	0x22, 0x05, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x22, 0x62, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x2c,
	0x0a, 0x0a, 0x62, 0x61, 0x72, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x72, 0x48,
	0x00, 0x52, 0x09, 0x62, 0x61, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0a,
	0x62, 0x61, 0x7a, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x7a, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a,
	0x0a, 0x62, 0x61, 0x72, 0x5f, 0x6f, 0x72, 0x5f, 0x62, 0x61, 0x7a, 0x42, 0x3b, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x63, 0x6f,
	0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x69, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x75, 0x74, 0x69,
	0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoutil_testpb_proto_rawDescOnce sync.Once
	file_protoutil_testpb_proto_rawDescData = file_protoutil_testpb_proto_rawDesc
)

func file_protoutil_testpb_proto_rawDescGZIP() []byte {
	file_protoutil_testpb_proto_rawDescOnce.Do(func() {
		file_protoutil_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoutil_testpb_proto_rawDescData)
	})
	return file_protoutil_testpb_proto_rawDescData
}

var file_protoutil_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoutil_testpb_proto_goTypes = []interface{}{
	(*Bar)(nil), // 0: testpb.Bar
	(*Foo)(nil), // 1: testpb.Foo
}
var file_protoutil_testpb_proto_depIdxs = []int32{
	0, // 0: testpb.Foo.bar_option:type_name -> testpb.Bar
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoutil_testpb_proto_init() }
func file_protoutil_testpb_proto_init() {
	if File_protoutil_testpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoutil_testpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoutil_testpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protoutil_testpb_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Foo_BarOption)(nil),
		(*Foo_BazOption)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoutil_testpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoutil_testpb_proto_goTypes,
		DependencyIndexes: file_protoutil_testpb_proto_depIdxs,
		MessageInfos:      file_protoutil_testpb_proto_msgTypes,
	}.Build()
	File_protoutil_testpb_proto = out.File
	file_protoutil_testpb_proto_rawDesc = nil
	file_protoutil_testpb_proto_goTypes = nil
	file_protoutil_testpb_proto_depIdxs = nil
}
